# Load data

In [ ]:
%pip install gdown

In [ ]:
!pip install -U --no-cache-dir gdown --pre

In [ ]:
#https://drive.google.com/file/d/1MCChTc9Rn-APN7Aq5h08qeTyRmw5TIg0/view?usp=sharing
!gdown --id 1MCChTc9Rn-APN7Aq5h08qeTyRmw5TIg0  #Lst21

Downloading...
From: https://drive.google.com/uc?id=1MCChTc9Rn-APN7Aq5h08qeTyRmw5TIg0
To: /content/LST21.zip
100% 381M/381M [00:03<00:00, 95.2MB/s]


In [ ]:
!unzip "/content/LST21.zip" -d "/content/LST21"

Streaming output truncated to the last 5000 lines.
  inflating: /content/LST21/LST21/lst21_9/797253.txt  
  inflating: /content/LST21/LST21/lst21_9/797254.txt  
  inflating: /content/LST21/LST21/lst21_9/797255.txt  
  inflating: /content/LST21/LST21/lst21_9/797256.txt  
  inflating: /content/LST21/LST21/lst21_9/797257.txt  
  inflating: /content/LST21/LST21/lst21_9/797259.txt  
  inflating: /content/LST21/LST21/lst21_9/797260.txt  
  inflating: /content/LST21/LST21/lst21_9/797261.txt  
  inflating: /content/LST21/LST21/lst21_9/797262.txt  
  inflating: /content/LST21/LST21/lst21_9/797263.txt  
  inflating: /content/LST21/LST21/lst21_9/797264.txt  
  inflating: /content/LST21/LST21/lst21_9/797265.txt  
  inflating: /content/LST21/LST21/lst21_9/797976.txt  
  inflating: /content/LST21/LST21/lst21_9/797977.txt  
  inflating: /content/LST21/LST21/lst21_9/797978.txt  
  inflating: /content/LST21/LST21/lst21_9/797979.txt  
  inflating: /content/LST21/LST21/lst21_9/797980.txt  
  inflating: /

In [ ]:
!unzip -qq /content/train2.zip #Lst21

In [ ]:
#https://drive.google.com/file/d/12sE7rIQmbArlOTxeVFjueg_G4LLjJTv6/view?usp=sharing
!gdown --id 12sE7rIQmbArlOTxeVFjueg_G4LLjJTv6   #Lst20

Downloading...
From: https://drive.google.com/uc?id=12sE7rIQmbArlOTxeVFjueg_G4LLjJTv6
To: /content/train2.zip
100% 14.5M/14.5M [00:00<00:00, 37.8MB/s]


In [ ]:
!unzip -qq /content/train2.zip #Lst20

# Import

In [ ]:
import pandas as pd
import tensorflow as tf
import pickle
import numpy as np
from sklearn.model_selection import train_test_split


# Preprocess

## data Lst20

In [ ]:
import os
path = '/content/train2'
wordss = []
poss = []
counter = 0
word = []
pos = []
for dir in sorted(os.listdir(path)):
    if dir != ".DS_Store" and dir.startswith('T'):
      #print(dir)
      f = open(os.path.join(path,dir), "r")

      #print(f.read())


      for i in f :
        #print(i.split())
        if len(i.split()) == 0 :
          
          wordss.append(word)
          poss.append(pos)
          word = []
          pos = []
          # print(wordss)
          # print(poss)
          continue
        word.append(i.split("\t")[0])
        pos.append(i.split("\t")[2])
        # if counter > 24:
        #   break
        # counter +=1

In [ ]:
wordss = list(filter(lambda x: len(x) <= 150, wordss))
poss=list(filter(lambda x: len(x) <= 150, poss))

In [ ]:
from sklearn.model_selection import train_test_split


wordss = list(filter(lambda x: len(x) <= 150, wordss))
poss = list(filter(lambda x: len(x) <= 150, poss))
tags=['B_BRN', 'B_DES', 'B_DTM', 'B_LOC', 'B_MEA', 'B_NUM', 'B_ORG', 'B_PER', 
      'B_TRM', 'B_TTL', 'E_BRN', 'E_DES', 'E_DTM', 'E_LOC', 'E_MEA', 'E_NUM', 
      'E_ORG', 'E_PER', 'E_TRM', 'E_TTL', 'I_BRN', 'I_DES', 'I_DTM', 'I_LOC', 
      'I_MEA', 'I_NUM', 'I_ORG', 'I_PER', 'I_TRM', 'I_TTL', 'O']
for ts in range(len(poss)):
  for tag in range(len(poss[ts])):
    if poss[ts][tag]=='ORG_I':
      poss[ts][tag]='I_ORG'

    elif poss[ts][tag]=='LOC_I':
      poss[ts][tag]='I_LOC'

    elif poss[ts][tag]=='PER_I':
      poss[ts][tag]='I_PER'
    elif poss[ts][tag] not in tags:
      poss[ts][tag]='O'
  
for s in range(len(wordss)) :
    for w in range(len(wordss[s])):
        try:
          a=float(wordss[s][w]) +1
          wordss[s][w]='NUM'
        except:
          pass
(train_sentences, test_sentences, train_tags, test_tags) = train_test_split(wordss, poss, test_size=0.2)

In [ ]:
word2index={}
word2index_save=[]
total_word=set()
tag2index = {t: i + 1 for i, t in enumerate(tags)}
tag2index['PAD'] = 0  

for i in wordss:
  for j in i:
    total_word.add(j)


word2index = { w :i + 2 for i, w in enumerate(wordss)}
word2index['PAD'] = 0  
word2index['UNK'] = 1   

# word2index_save = list((w ,i + 2 ) for i, w in enumerate(wordss))
# word2index_save.append(('PAD',0))
# word2index_save.append(('UNK',1))
# df=pd.DataFrame(word2index_save,columns=['words','indexs'])
# df.to_csv('/content/my_dict.csv')
# df

### Save dict

In [ ]:
# pickle.dump(word2index, open('/content/dict_word.p', 'wb'), protocol =4)
# # with open('/content/drive/MyDrive/SUPERAI2-452 /NLP#1/cat_train_tags_y_3.p', "rb") as fh:
# #   cat_train_tags_y = pickle.load(fh)

In [ ]:
train_sentences_X, test_sentences_X, train_tags_y, test_tags_y = [], [], [], []
 
for s in train_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w]) #.lower()])
        except KeyError:
            s_int.append(word2index['UNK'])
 
    train_sentences_X.append(s_int)
 
for s in test_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w]) 
        except KeyError:
            s_int.append(word2index['UNK'])
 
    test_sentences_X.append(s_int)

for s in train_tags:
    a=[]
    for t in s:
        try:
            a.append(tag2index[t])
        except:
            a.append(tag2index['O'])
    train_tags_y.append(a)
for s in test_tags:
    a=[]
    for t in s:
        try:
            a.append(tag2index[t])
        except:
            a.append(tag2index['O'])
    test_tags_y.append(a)
    
#print(train_sentences_X[0])
#print(test_sentences_X[0])
#print(train_tags_y[0])
#print(test_tags_y[0])

## Data Lst21

In [ ]:
import pandas as pd
import os
path_lst21_1 = '/content/LST21/LST21/lst21_1/'
word21=[[]]
tag21=[[]]
for file in sorted(os.listdir(path_lst21_1)):
  text = pd.read_csv(path_lst21_1+file , sep=' /', header=None, skip_blank_lines=False)
  text=text.fillna(' ')
  for sent in text[0]:
    if sent!=' ':
      word21[len(word21)-1].append(sent.split('\t')[0])
      tag21[len(tag21)-1].append(sent.split('\t')[2])
    else:
      word21.append([])
      tag21.append([])
del word21[-1]
del tag21[-1]

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


In [ ]:
a=0
for i in word21:
  if len(i)>150:
    a +=1
a

In [ ]:
from sklearn.model_selection import train_test_split


word21 = list(filter(lambda x: len(x) <= 150, word21))
tag21 = list(filter(lambda x: len(x) <= 150, tag21))
tags=['B_BRN', 'B_DES', 'B_DTM', 'B_LOC', 'B_MEA', 'B_NUM', 'B_ORG', 'B_PER', 
      'B_TRM', 'B_TTL', 'E_BRN', 'E_DES', 'E_DTM', 'E_LOC', 'E_MEA', 'E_NUM', 
      'E_ORG', 'E_PER', 'E_TRM', 'E_TTL', 'I_BRN', 'I_DES', 'I_DTM', 'I_LOC', 
      'I_MEA', 'I_NUM', 'I_ORG', 'I_PER', 'I_TRM', 'I_TTL', 'O']
for ts in range(len(tag21)):
  for tag in range(len(tag21[ts])):
    if tag21[ts][tag]=='ORG_I':
      tag21[ts][tag]='I_ORG'

    elif tag21[ts][tag]=='LOC_I':
      tag21[ts][tag]='I_LOC'

    elif tag21[ts][tag]=='PER_I':
      tag21[ts][tag]='I_PER'
    elif tag21[ts][tag] not in tags:
      tag21[ts][tag]='O'
  
for s in range(len(word21)) :
    for w in range(len(word21[s])):
        try:
          a=float(word21[s][w]) +1
          word21[s][w]='NUM'
        except:
          pass
(train_sentences, test_sentences, train_tags, test_tags) = train_test_split(word21, tag21, test_size=0.2)

### Load dict

In [ ]:
# with open('/content/dict_word.p', "rb") as fh:
#   word2index = pickle.load(fh)

In [ ]:
sample_submission=[]
for i,sent in enumerate(sentence_list):
  for j, word in enumerate(sent):
    sample_submission.append(submis[i][j])

        

In [ ]:
word2index={}
word2index_save=[]
total_word=set()
tag2index = {t: i + 1 for i, t in enumerate(tags)}
tag2index['PAD'] = 0  

for i in word21:
  for j in i:
    total_word.add(j)


word2index = { w :i + 2 for i, w in enumerate(list(total_word))}
word2index['PAD'] = 0  
word2index['UNK'] = 1   

# pickle.dump(word2index, open('/content/dict_word.p', 'wb'), protocol =4)


In [ ]:
train_sentences_X, test_sentences_X, train_tags_y, test_tags_y = [], [], [], []
 
for s in train_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w]) #.lower()])
        except KeyError:
            s_int.append(word2index['UNK'])
 
    train_sentences_X.append(s_int)
for s in test_sentences:
    s_int = []
    for w in s:
        try:
            s_int.append(word2index[w]) 
        except KeyError:
            s_int.append(word2index['UNK'])
 
    test_sentences_X.append(s_int)
for s in train_tags:
    a=[]
    for t in s:
        try:
            a.append(tag2index[t])
        except:
            a.append(tag2index['O'])
    train_tags_y.append(a)
for s in test_tags:
    a=[]
    for t in s:
        try:
            a.append(tag2index[t])
        except:
            a.append(tag2index['O'])
    test_tags_y.append(a)

# Model

In [ ]:
# import tensorflow as tf
# model = tf.keras.models.load_model('../input/model-lst20/model_NER_Pgot.h5')

In [ ]:
MAX_LENGTH = len(max(train_sentences_X, key=len))
print(MAX_LENGTH)  # 271

80


In [ ]:
from keras.preprocessing.sequence import pad_sequences

train_sentences_X = pad_sequences(train_sentences_X, maxlen=MAX_LENGTH, padding='post')
test_sentences_X = pad_sequences(test_sentences_X, maxlen=MAX_LENGTH, padding='post')
train_tags_y = pad_sequences(train_tags_y, maxlen=MAX_LENGTH, padding='post')
test_tags_y = pad_sequences(test_tags_y, maxlen=MAX_LENGTH, padding='post')
 
#print(train_sentences_X[0])
#print(test_sentences_X[0])
#print(train_tags_y[0])
#print(test_tags_y[0])

In [ ]:
!python --version

Python 3.7.12


In [ ]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, InputLayer, Bidirectional, TimeDistributed, Embedding, Activation
from tensorflow.keras.optimizers import Adam, SGD, RMSprop
 
 
model = Sequential()
model.add(InputLayer(input_shape=(MAX_LENGTH, )))
model.add(Embedding(len(word2index), 100))
# model.add(keras.layers.Conv1D(1, (4,4), activation='relu',strides=4))
# model.add(keras.layers.MaxPool1D(pool_size=2, strides=2)) 
# model.add(keras.layers.Conv1D(1, (4,4), activation='relu',strides=4))
# model.add(keras.layers.MaxPool1D(pool_size=2, strides=2)) 
# model.add(Flatten())

model.add(Bidirectional(LSTM(128, return_sequences=True)))
model.add(tf.keras.layers.Dropout(0.2))
model.add(TimeDistributed(Dense(len(tag2index))))
model.add(Activation('softmax'))
 
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(0.001),
              metrics=['accuracy'])
 
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 80, 128)           16380928  
                                                                 
 bidirectional (Bidirectiona  (None, 80, 512)          788480    
 l)                                                              
                                                                 
 time_distributed (TimeDistr  (None, 80, 32)           16416     
 ibuted)                                                         
                                                                 
 activation (Activation)     (None, 80, 32)            0         
                                                                 
Total params: 17,185,824
Trainable params: 17,185,824
Non-trainable params: 0
_________________________________________________________________


In [ ]:
def to_categorical(sequences, categories):
    cat_sequences = []
    for s in sequences:
        cats = []
        for item in s:
            cats.append(np.zeros(categories))
            cats[-1][item] = 1.0
        cat_sequences.append(cats)
    return np.array(cat_sequences)

In [ ]:
train_tags_y, train_tags_y.shape

(array([[31, 31, 31, ...,  0,  0,  0],
        [ 7, 24, 17, ..., 31, 31, 31],
        [31, 30, 31, ...,  0,  0,  0],
        ...,
        [31,  7, 31, ..., 13,  0,  0],
        [ 4, 14, 31, ...,  0,  0,  0],
        [31, 31, 31, ...,  0,  0,  0]], dtype=int32), (70494, 80))

In [ ]:
train_tags_y[0]
print(len(tag2index))

32


In [ ]:
import numpy as np

cat_train_tags_y = to_categorical(train_tags_y, len(tag2index))
print(cat_train_tags_y[0])

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
model.fit(train_sentences_X, to_categorical(train_tags_y, len(tag2index)), batch_size=32, epochs=5, validation_split=0.2)

Epoch 1/5
 414/1763 [======>.......................] - ETA: 16:28 - loss: 0.3378 - accuracy: 0.9338

In [ ]:
scores = model.evaluate(test_sentences_X, to_categorical(test_tags_y, len(tag2index)))
print(f"{model.metrics_names[1]}: {scores[1] * 100}")

In [ ]:
model.save('/content/model_NER_Pgot.h5')

# Predict

In [ ]:
def logits_to_tokens(sequences, index):
    token_sequences = []
    for categorical_sequence in sequences:
        token_sequence = []
        for categorical in categorical_sequence:
            token_sequence.append(index[np.argmax(categorical)])
            
        token_sequences.append(token_sequence)
 
    return token_sequences

## try

In [ ]:
a='และ ยืนยัน ว่า ประชาชน ใน ภาค ใต้ ไม่ มีการ ซื้อ เสียง'
test_samples=[a.split()]
print(test_samples)# = [['นาง','สุดารัตน์','เกยุราพันธ์','รมว.','สาธารณสุข']]

In [ ]:
test_samples_X = []
for s in test_samples:
    print(s)
    s_int = []
    
    for w in s:
        try:
            s_int.append(word2index[w]) #.lower()])
            print(s_int)
        except KeyError:
            s_int.append(word2index['-UNK-'])
    test_samples_X.append(s_int)
 
test_samples_X = pad_sequences(test_samples_X, maxlen=MAX_LENGTH, padding='post')
print(test_samples_X)

In [ ]:
predictions = model.predict(test_samples_X)
print(predictions, predictions.shape)

In [ ]:
print(logits_to_tokens(predictions, {i: t for t, i in tag2index.items()}))

## Submission1

In [ ]:
#https://drive.google.com/file/d/17tcUt5uTkCS2hx5i7lxhKnQpBBijCc5G/view?usp=sharing
!gdown --id 17tcUt5uTkCS2hx5i7lxhKnQpBBijCc5G

In [ ]:
import pandas as pd
import os
path_test = '/content/ne_test.txt'
ne_test_pd = pd.read_csv(path_test, sep=' /', header=None, skip_blank_lines=False)
ne_test_pd=ne_test_pd.fillna('_')

In [ ]:
check_predict=[]
test_samples_X=[]
for s in ne_test_pd[0]:
    try:
        try:
          a=float(s)+1
          test_samples_X.append('NUM')
        except:
          test_samples_X.append(word2index[s]) #.lower()])
          check_predict.append(s)
    except KeyError:
        test_samples_X.append(word2index['UNK'])
        check_predict.append('UNK')

nu_test_sent = []
check_pred=[]
for i in range(0,len(test_samples_X),MAX_LENGTH):
  nu_test_sent.append(test_samples_X[i:i+MAX_LENGTH])
  check_pred.append(check_predict[i:i+MAX_LENGTH])

a=len(nu_test_sent[-1]) 
b=len(nu_test_sent)
for i in range(MAX_LENGTH-a):
  nu_test_sent[-1].append(word2index['PAD']) # PAD last index
  check_pred[-1].append('PAD')

In [ ]:
nu_test_sent=np.array(nu_test_sent)
# nu_test_sent=tf.data.Dataset.from_tensor_slices(nu_test_sent)

In [ ]:
predictions = model.predict(nu_test_sent)
print(predictions, predictions.shape)

In [ ]:
submis=logits_to_tokens(predictions, {i: t for t, i in tag2index.items()})
print(logits_to_tokens(predictions, {i: t for t, i in tag2index.items()}))

In [ ]:
sample_submission=[]
for i in submis:
  for j in i:
    # if j=='-PAD-': break
    sample_submission.append(j)


In [ ]:
len(sample_submission)

In [ ]:
len(test_samples_X)

In [ ]:
sub  =  sample_submission[0:len(test_samples_X)-1]
print(len(sub))

In [ ]:
num_csv=np.arange(69562).tolist()
print(num_csv[-1])

In [ ]:
ne_test_pd

In [ ]:
sub_csv = []
for n, i in enumerate(sub):
  sub_csv.append([n+1, i])

In [ ]:
pd.DataFrame(sub_csv, columns=['Id','Predicted']).to_csv(f'submission.csv', index=None)

In [ ]:
df=pd.DataFrame([num_csv,sub],columns=['Id','Predicted'],index=False)
df.to_csv('/content/sample_submission.csv')

In [ ]:
print(check_pred[0])
print(submis[0])